//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Getix_Admin_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int Config_Id { get; set; }
        public string Config_Name { get; set; }
        public int Project_Id { get; set; }
        public System.DateTime RowInsertDate { get; set; }
        public string RowInsertBy { get; set; }
    }
}
