//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Getix_Admin_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectColumn
    {
        public int ProjectColumnId { get; set; }
        public int ProjectId { get; set; }
        public int ProjectTableID { get; set; }
        public string CoulmnName { get; set; }
        public string Datatype { get; set; }
        public System.DateTime RowInsertDate { get; set; }
    }
}
