//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Getix_Admin_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableColumn
    {
        public int id { get; set; }
        public string name { get; set; }
        public string tableType { get; set; }
        public string columnNames { get; set; }
        public int projectId { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
