//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Getix_Admin_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int User_id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string WindowsLogin { get; set; }
        public string UsrEmail { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Row_inserted_Date { get; set; }
        public Nullable<System.DateTime> Row_updated_Date { get; set; }
    }
}
